apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  - secrets.yaml
  - docker-registry-secret.yaml

namespace: trading-bot  # Change this to your preferred namespace
