apiVersion: v1
kind: Service
metadata:
  name: trading-bot
  labels:
    app: trading-bot
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort if you need external access
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: trading-bot
